version: '3'
services:
  bcoin-node:
    build: .
    ports:
      - '8332:8332' # main
      - '18332:18332' # testnet
      - '18556:18556' # default simnet
      - '48332:48332' # regtest
    volumes:
      - ./.bcoin/:~/.bcoin/:ro